
services:
  omsauthapi:
    build:
      context: ../src/OmsAuthApi/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8081
    restart: always
